name: Custom Env Workflow

run-name: Pipeline run by @${{ github.actor }}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DAY_OF_WEEK: "Monday"
  testvar: "testvar"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mainjob:
    name: "Print Env"
    runs-on: arc-runner-set

    env:
      Greetings: "Hi"
      testvar: "testvar2"

    steps:
      - name: Print Env
        run: |
          echo "Greetings: ${{ env.Greetings }}"
          echo "testvar: ${{ env.testvar }}"
          echo "DAY_OF_WEEK: ${{ env.DAY_OF_WEEK }}"
        env:
          testvar: "testvar3"
          First_Name: "John"
    
  second-job:
    name: "Print Env"
    runs-on: arc-runner-set

    env:
      Greetings: "Hi"
      testvar: "testvar2"

    steps:
      - name: Print Env
        run: |
          echo "Greetings: ${{ env.Greetings }}"
          echo "testvar: ${{ env.testvar }}"
          echo "DAY_OF_WEEK: ${{ env.DAY_OF_WEEK }}"
        env:
          testvar: "testvar3"
          First_Name: "John"
  
  report-url:
    name: print report url
    runs-on: arc-runner-set

    steps:
      - name: print report url
        run: |
          echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      
      - name: check-os
        if: runner.os != 'Windows'
        run: |
          echo "This runner operating system is $RUNNER_OS."
